name: Build and push docker image

on:
  push:
    branchs: [main]

jobs:
  builds-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker build
      run: hostnamectl 

         
         #docker build -t netfix_backend: latest .
      
  